pipelines:
  branches:
    master:
      - step:
          name: Build
          image: bitbucketpipelines/android-ci-image
          caches:
            - gradle
          script:
            - chmod +x ./gradlew
            - ./gradlew assembleRelease
          artifacts:
            - app/build/outputs/**
